spring:
  profiles:
    active: prod

  main:
    lazy-initialization: false

  # Database connection settings
  datasource:
    url: jdbc:h2:./db/ptai
    username: sa
    password: P@ssw0rd
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: false

# Logging settings
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.cloud.consul: ERROR
    com.ptsecurity.appsec.ai.ee.utils.ci.integration.service: DEBUG


# Spring Boot Actuator endpoints
endpoints:
  health.sensitive: false
  info.sensitive: false
  metrics.sensitive: false
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health.enabled: true
  security:
    enabled: false

# Enable SSL
security:
  require-ssl: true
server:
  error:
    include-stacktrace: never
  ssl:
    # SSL settings for integration service HTTPS access
    key-store-type: JKS
    key-store: classpath:file:///C:/TOOLS/jdk1.8/jre/lib/security/cacerts
    key-store-password: changeit
    key-alias: ssl server certificate
    key-password: P@ssw0rd
    trust-store-type: JKS
    trust-store: classpath:file:///C:/TOOLS/jdk1.8/jre/lib/security/cacerts
    trust-store-password: changeit
  port: 8443

# PT AI backend services settings
ptai-backend-services:
  # Backend services settings
  #
  # Location of embedded CI server
  ci-url: https://ptaisrv.domain.org:8080
  # User name and access token for embedded CI server
  ci-user-name: svc_ptai
  # api-token: 114b330974dba8827019a5988ed461f8af
  ci-api-token: 111ce2b51500cff0df832059e422c01329
  ci-job-name: PTAI/SAST
  # As Jenkins connection may be unstable due to its load, sometimes there's need for retries
  ci-max-retry: 5
  ci-retry-delay: 5000

  # SSL client key to authenticate on PTAI server
  ptai-key-alias: ssl client certificate
  ptai-key-password: P@ssw0rd
  # URL of PTAI server gateway.
  ptai-url: https://ptaisrv.domain.org:443

ptai-integration-service:
  # Certificate alias to use to check JWT
  check-cert-alias: domain.org ptai authorization server (alzhukov-pc.ptsecurity.ru)

# There is embedded authorization server that uses the same keystore as server.ssl.key-store
ptai-authorization-server:
  # User name that is created in the authorization server DB
  admin-name: admin
  # Key alias to use to sign JWT
  sign-key-alias: domain.org ptai authorization server (alzhukov-pc.ptsecurity.ru)
  sign-key-password: 1q2w3e4r
